version: 2

jobs:
  lint:
    parallelism: 1

    docker:
      - image: circleci/node:10.15

    working_directory: ~/mock-oidc-user-server

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

  build:
    machine: true
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Build Image
          command: docker build -t appvia/mock-oidc-user-server:$CIRCLE_SHA1 .

  push_latest:
    machine: true
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Push to Quay with tag latest
          command: |
            docker build -t quay.io/appvia/mock-oidc-user-server:latest .
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker push quay.io/appvia/mock-oidc-user-server:latest

  push_tag:
    machine: true
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Push to Quay with Git tag
          command: |
            docker build -t quay.io/appvia/mock-oidc-user-server:$CIRCLE_TAG .
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker push quay.io/appvia/mock-oidc-user-server:$CIRCLE_TAG

workflows:
  version: 2
  main:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/

      - build:
          requires:
            - lint
          filters:
            tags:
              only: /.*/

      - push_latest:
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/

      - push_tag:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
